### ISSUE TITLE
needs scan_by_url

### ISSUE THREAD

**Issue by ILG2021** [bropines/chrome-lens-py#3]

**Comment by bropines** [comment]
Is it really necessary? I kind of can, but...... Okaaaaaaaay, I'll do it by the end of the week.

**Comment by ILG2021** [comment]
> Is it really necessary? I kind of can, but...... Okaaaaaaaay, I'll do it by the end of the week.

yes, really. Many online images need to recognize.

**Comment by bropines** [comment]
@ILG2021 sorry, I've been a bit delayed(dealing with uni issues). I added. It's kinda working. I released a version on pypi so just do the upgrade

**Comment by ILG2021** [comment]
> @ILG2021 sorry, I've been a bit delayed(dealing with uni issues). I added. It's kinda working. I released a version on pypi so just do the upgrade

Thank you very much.

**Comment by bropines** [comment]
> > > @ILG2021 sorry, I've been a bit delayed(dealing with uni issues). I added. It's kinda working. I released a version on pypi so just do the upgrade
> 
> Thank you very much.

Can you check everything you need (I did but I'm crooked) for me to close ISSUE?

**Comment by ILG2021** [comment]
can not install logging package, it is a build in package.

**Comment by ILG2021** [comment]
Error downloading or processing image from URL: Error processing image from buffer: Failed to convert expires 'Thu, 17-Apr-2025 23:52:11 GMT' to timestamp: Invalid date value or format

**Comment by ILG2021** [comment]
fixed by:
cookies_manager.py
```
@staticmethod
def ensure_timestamp(expires):
"""Ensures that the expires value is a Unix timestamp."""
if isinstance(expires, (int, float)):
	return expires
if isinstance(expires, str):
	try:
		return float(expires)
	except ValueError:
		print(f"Failed to convert expires '{expires}' to timestamp: Invalid date value or format")
		try:
			dt = datetime.strptime(expires, '%a, %d-%b-%Y %H:%M:%S GMT')
			timestamp = dt.timestamp()
			return float(timestamp)
		except Exception as e:
			print(e)
return expires
```

**Comment by bropines** [comment]
I'll fix it by evening.

**Comment by bropines** [comment]
> fixed by: cookies_manager.py
> 
> ```
> @staticmethod
> def ensure_timestamp(expires):
> """Ensures that the expires value is a Unix timestamp."""
> if isinstance(expires, (int, float)):
> 	return expires
> if isinstance(expires, str):
> 	try:
> 		return float(expires)
> 	except ValueError:
> 		print(f"Failed to convert expires '{expires}' to timestamp: Invalid date value or format")
> 		try:
> 			dt = datetime.strptime(expires, '%a, %d-%b-%Y %H:%M:%S GMT')
> 			timestamp = dt.timestamp()
> 			return float(timestamp)
> 		except Exception as e:
> 			print(e)
> return expires
> ```

Looks like it's fixed. Now there is also a debug mode which, if something happens, will even give you a whole response from lens for independent analysis. Sorry for the delay
