### ISSUE TITLE
Default configuration path

### ISSUE THREAD

**Issue by kqvanity** [bropines/chrome-lens-py#5]
Could you define a default path to look up for overall CLI tool default configuration/previous cookies e.g., $XDG_CONFIG_HOME

**Comment by bropines** [comment]
Okay, I'll add it tomorrow

**Comment by bropines** [comment]
Try it, added

**Comment by kqvanity** [comment]
Thanks!

Just one additional question. I see you load the cookies file from `~/.local/share/pipx/venvs/chrome-lens-py/lib/python3.12/site-packages/chrome_lens_py/cookies.pkl` or equivalent path. Is it redundant for me to explicitly save the one obtained from the debug info?

**Comment by bropines** [comment]
> Thanks!
> 
> Just one additional question. I see you load the cookies file from `~/.local/share/pipx/venvs/chrome-lens-py/lib/python3.12/site-packages/chrome_lens_py/cookies.pkl` or equivalent path. Is it redundant for me to explicitly save the one obtained from the debug info?

To a large extent, I did this logging for myself. And also, I seem to have moved the cookie to the default config folder, for convenience. I can remove unnecessary logs and leave what is needed, dividing it into different logging levels

**Comment by kqvanity** [comment]
> I seem to have moved the cookie to the default config folder, 

sorry my bad.

> I can remove unnecessary logs and leave what is needed

They're great. Logs are always useful. maybe just a configurable path to save them or defaulting to the /tmp directory instead of CWD

**Comment by bropines** [comment]
> > I seem to have moved the cookie to the default config folder,
> 
> sorry my bad.
> 
> > I can remove unnecessary logs and leave what is needed
> 
> They're great. Logs are always useful. maybe just a configurable path to save them or defaulting to the /tmp directory instead of CWD

But.... I got it, okay, I think it's even better this way. Should I make it a separate flag, or let it default to TMP?

**Comment by kqvanity** [comment]
Probably a flag to be OS-agnostic (unless python abstracts away such directories e.g., config, tmp, etc)

**Comment by bropines** [comment]
Did it. Now you can specify the path where to save the debug file.

**Comment by kqvanity** [comment]
Thank you!
