### ISSUE TITLE
to process batch images

### ISSUE THREAD

**Issue by truthsayer969** [bropines/chrome-lens-py#6]
bro, thanks a lot for this tool. If i want to do OCR for a batch of images, what kind of command should be used?

**Comment by bropines** [comment]
Well, there is no built-in batch processing tool. I might add.  But in what form?
Text document with a list? A folder with pictures?
The question is also in what format to give them to you....

In fact, the library itself can be used from the Python API. And the same GPT, if you feed it documentation, will understand what and how to use, and will also write batch processing for you. Decide for yourself, I can add, but I will have to think for a long time in what form to give the data

**Comment by truthsayer969** [comment]
Thank you very much for the reply, Bro,
I think, simple text files will be ok. For example, there will be an input folder which has a batch of image files of jpg or jpeg formats, the output folder has text files with the same name as the input image files (one  output text file for each of an input image file).

**Comment by bropines** [comment]
I will release an update by the evening

**Comment by truthsayer969** [comment]
> I will release an update by the evening

thank you very much, bro

**Comment by bropines** [comment]
@truthsayer969
Go Test
```bash
pip install -U chrome-lens-py
```

Something like this
```bash
 lens_scan "PATH" full_text_default
 ```

**Comment by truthsayer969** [comment]
thank bro, i tested cli method, when i just tested 
with a batch of a few image, it works. But when i add such as 50 images, it does not work, resulting a blank txt file

**Comment by bropines** [comment]
> thank bro, i tested cli method, when i just tested with a batch of a few image, it works. But when i add such as 50 images, it does not work, resulting a blank txt file

Is there a log? It always outputs logs

**Comment by truthsayer969** [comment]
> > thank bro, i tested cli method, when i just tested with a batch of a few image, it works. But when i add such as 50 images, it does not work, resulting a blank txt file
> 
> Is there a log? It always outputs logs

Dear Bro, now i can do OCR for a batch of 48 files, but it does not produce log file, so i am unable to show you.
By the way, it takes 4-5 min to do OCR for these 48 images how can i speed it up?
Would you kindly make the tool to produce a separate text file for each image? text file should have the same name as the input image file.

I run it like this:
lens_scan "C:/Users/HP/Downloads/python_tests/chrome-lens-py-1.3.0/chrome-lens-py-1.3.0/New folder" full_text_default

**Comment by bropines** [comment]
> > > thank bro, i tested cli method, when i just tested with a batch of a few image, it works. But when i add such as 50 images, it does not work, resulting a blank txt file
> > 
> > 
> > Is there a log? It always outputs logs
> 
> Dear Bro, now i can do OCR for a batch of 48 files, but it does not produce log file, so i am unable to show you. By the way, it takes 4-5 min to do OCR for these 48 images how can i speed it up? Would you kindly make the tool to produce a separate text file for each image? text file should have the same name as the input image file.

1. The log is issued in the console, and if something went wrong, it will report it directly in the console.
2. Yes, I will update the code so that you can create a text document for each file for each file. But if you need to use the recognition of 10-1000 images, then I suggest you stupidly put https://github.com/dmMaze/BallonsTranslator in which you can both recognize and translate....
3. The speed of recognition depends on 2 factors. Your Internet, which transmits requests (goes to lens) and the delay itself is
`--sleep-time`, which you can set manually, but you can not set less than 300ms

**Comment by truthsayer969** [comment]
> > > > thank bro, i tested cli method, when i just tested with a batch of a few image, it works. But when i add such as 50 images, it does not work, resulting a blank txt file
> > > 
> > > 
> > > Is there a log? It always outputs logs
> > 
> > 
> > Dear Bro, now i can do OCR for a batch of 48 files, but it does not produce log file, so i am unable to show you. By the way, it takes 4-5 min to do OCR for these 48 images how can i speed it up? Would you kindly make the tool to produce a separate text file for each image? text file should have the same name as the input image file.
> 
>     1. The log is issued in the console, and if something went wrong, it will report it directly in the console.
> 
>     2. Yes, I will update the code so that you can create a text document for each file for each file. But if you need to use the recognition of 10-1000 images, then I suggest you stupidly put  [https://github.com/dmMaze/BallonsTranslator ](https://github.com/dmMaze/BallonsTranslator) in which you can both recognize and translate....
> 
>     3. The speed of recognition depends on 2 factors. Your Internet, which transmits requests (goes to lens) and the delay itself is 
>        `--sleep-time`, which you can set manually, but you can not set less than 300ms

Thank you very much, bro, for the explanation. Yes, I admit that my internet is not fast.
I will wait for the update.

**Comment by bropines** [comment]
I made it, I'm testing it

**Comment by bropines** [comment]
> > > > > thank bro, i tested cli method, when i just tested with a batch of a few image, it works. But when i add such as 50 images, it does not work, resulting a blank txt file
> > > > 
> > > > 
> > > > Is there a log? It always outputs logs
> > > 
> > > 
> > > Dear Bro, now i can do OCR for a batch of 48 files, but it does not produce log file, so i am unable to show you. By the way, it takes 4-5 min to do OCR for these 48 images how can i speed it up? Would you kindly make the tool to produce a separate text file for each image? text file should have the same name as the input image file.
> > 
> > 
> > ```
> > 1. The log is issued in the console, and if something went wrong, it will report it directly in the console.
> > 
> > 2. Yes, I will update the code so that you can create a text document for each file for each file. But if you need to use the recognition of 10-1000 images, then I suggest you stupidly put  [https://github.com/dmMaze/BallonsTranslator ](https://github.com/dmMaze/BallonsTranslator) in which you can both recognize and translate....
> > 
> > 3. The speed of recognition depends on 2 factors. Your Internet, which transmits requests (goes to lens) and the delay itself is 
> >    `--sleep-time`, which you can set manually, but you can not set less than 300ms
> > ```
> 
> Thank you very much, bro, for the explanation. Yes, I admit that my internet is not fast. I will wait for the update.

Done. Test it.

**Comment by bropines** [comment]
@truthsayer969 work?

**Comment by truthsayer969** [comment]
> @truthsayer969 work?

Dear Bro, It works. I tested with scan images of books. I already finished 2 books, each has 200-300 pages and it works perfectly.
Thank you very much for this wonderful tool.

**Comment by bropines** [comment]
> Dear Bro, It works. I tested with scan images of books. I already finished 2 books, each has 200-300 pages and it works perfectly.
> Thank you very much for this wonderful tool.

Maybe you can use the program that I dropped above? It also contains the same library, and will allow you to work with text faster.

**Comment by bropines** [comment]
And I think I'll close the ISSUE

**Comment by truthsayer969** [comment]
> > Dear Bro, It works. I tested with scan images of books. I already finished 2 books, each has 200-300 pages and it works perfectly.
> > Thank you very much for this wonderful tool.
> 
> Maybe you can use the program that I dropped above? It also contains the same library, and will allow you to work with text faster.

thanks bro, for the advice, I will try it also.

**Comment by truthsayer969** [comment]
> And I think I'll close the ISSUE

ok, bro, Thank you very much for you kindness to explain me and update of the tool.

**Comment by timminator** [comment]
Can it be that batch processing images is no longer working in the latest release?

I tried it like this:
```
lens_scan "C:\Users\GPUVM\Pictures\New folder (2)" ch
```

But I got:
```
Error: Source 'C:\Users\GPUVM\Pictures\New folder (2)' is not a valid URL or supported image file.
```

**Comment by bropines** [comment]
> Может ли быть так, что пакетная обработка изображений больше не работает в последнем релизе?
> 
> Я попробовал так:
> 
> ```
> lens_scan "C:\Users\GPUVM\Pictures\New folder (2)" ch
> ```
> 
> But I got:
> 
> ```
> Error: Source 'C:\Users\GPUVM\Pictures\New folder (2)' is not a valid URL or supported image file.
> ```

I will fix it later

**Comment by bropines** [comment]
> Can it be that batch processing images is no longer working in the latest release?
> 
> I tried it like this:
> 
> ```
> lens_scan "C:\Users\GPUVM\Pictures\New folder (2)" ch
> ```
> 
> But I got:
> 
> ```
> Error: Source 'C:\Users\GPUVM\Pictures\New folder (2)' is not a valid URL or supported image file.
> ```

fixed

**Comment by timminator** [comment]
Works! Thank you.

One last question: The sleep time parameter mentioned in one of the posts here in this thread does no longer exists as far as I can see. Our processing speed is now just depending on sending the picture and awaiting the response from the API right?

**Comment by bropines** [comment]
> Works! Thank you.
> 
> One last question: The sleep time parameter mentioned in one of the posts here in this thread does no longer exists as far as I can see. Our processing speed is now just depending on sending the picture and awaiting the response from the API right?

Yes. There, Google himself will ban you if necessary. But if necessary, I can and manually limit)))
